### ISSUE TITLE
More Mask

### ISSUE THREAD

**Issue by anhdoantm** [Glagan/SimpleNotification#10]
Hi, @Glagan Notification is very nice and light

There is no Mask
Add Mask option
- Add a background **Mask** : **option**

- text: 'Content', is it possible to add comprehensive **Html**? For example: **Content.html** or **Div**.

**Comment by Glagan** [comment]
Hi, thanks for using SimpleNotification :)

I don't understand your request, what is a **background Mask** ?  
If you want to change or even remove the background you can use a custom notification type and create your own CSS class, or update the default one to remove it.

Also, what do you mean by **Content**, you can access the **body** of the notification like this:
```Javascript
const notification = SimpleNotification.info({
  text: 'Example'
});
notification.text.textContent = 'Test';
// notification.text is the <div> with the content
// You can also use notification.body which is the parent of notification.text
```

**Comment by anhdoantm** [comment]
Yes, thanks for the quick help.

- Sometimes still needing advanced customization with .innerHTML.

- Background around when **MODAL** pops up is blurred. Most MODAL have that.

But this must be optional, because not all notifications are used to it.
background as shown below.

**css example:**
.a-modal {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    **background-color: rgba(0,0,0,0.4);**
    z-index: 999999999;
    font-size: 1.1rem;
}

![Ảnh chụp màn hình (21)](https://user-images.githubusercontent.com/30150983/86934793-524fae00-c166-11ea-80df-48ae715330bd.png)

**Comment by Glagan** [comment]
Well, I'm sorry but this isn't what SimpleNotification is doing, you want, like you said, a **Modal**, SimpleNotification just make **notifications**.

I don't think adding a background to the whole page when there is only a notification in a corner is a good thing, and I also can't simulate a Modal since I didn't add a *center center* position.

I also can't add what you want with the raw HTML, since having a reference to the function would break the check of it existing, even if it's not used by default.  
You can still do it yourself like I said in my previous comment, but I understand it's not the best way to use it...

**Comment by anhdoantm** [comment]
Yeah okay .
But most announcements have this feature, because Modal or notice it is similar.
I am sure many people also want this option for a notification.

**Comment by Glagan** [comment]
I'm sorry but I won't add a background option that covers the whole page, I don't think it has it's place here, if you want to do that you can use a Modal library.  
If you still want to add it you can contribute or try to play with the CSS to make it work with how it is right now.
