### ISSUE TITLE
Feature request: more notification location options

### ISSUE THREAD

**Issue by ajmeese7** [Glagan/SimpleNotification#6]
Right now I have my notifications displayed in the center of the bottom of my page, which wasn't that hard to customize myself, but it would be cool if there was a way to specify `location: "bottomCenter"` as an option or something similar. This is my current hacked way of getting it to display how I want:
```
.gn-wrapper {
    position: absolute;
    bottom: 0;
    width: 100%;
    overflow: hidden;
    pointer-events: none;
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
    z-index: 1080;
}
```

Depending on the layout of the page, displaying in the center from the top or the bottom might be very visually attractive. This is what a notification looks like in my application:

![](https://cdn.discordapp.com/attachments/608041937261559858/617424587290050560/Screenshot_20190831-132440_Coupon_Booked.jpg)

Coming from the bottom and being centered makes it best for my use case.

**Comment by Glagan** [comment]
I added it in 47f3c72, positions are just CSS classes so I just added them.

I also added the ``insert-bottom`` animations you provided, and a top-center position also with it's animation.
I'm not going to make a release since I'm not really proud of the code to actually start the animation *life*, I will do make one when I resolve #5.
